// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package loginRegistration;

public interface changePasswordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginRegistration.changePassword)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emailId = 1;</code>
   * @return The emailId.
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 1;</code>
   * @return The bytes for emailId.
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();

  /**
   * <code>string oldPassword = 2;</code>
   * @return The oldPassword.
   */
  java.lang.String getOldPassword();
  /**
   * <code>string oldPassword = 2;</code>
   * @return The bytes for oldPassword.
   */
  com.google.protobuf.ByteString
      getOldPasswordBytes();

  /**
   * <code>string newPassword = 3;</code>
   * @return The newPassword.
   */
  java.lang.String getNewPassword();
  /**
   * <code>string newPassword = 3;</code>
   * @return The bytes for newPassword.
   */
  com.google.protobuf.ByteString
      getNewPasswordBytes();
}
