// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package loginRegistration;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRegistration_registration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRegistration_registration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRegistration_changePassword_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRegistration_changePassword_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRegistration_response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRegistration_response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loginRegistration_login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loginRegistration_login_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Hello.proto\022\021loginRegistration\"?\n\014regi" +
      "stration\022\014\n\004name\030\001 \001(\t\022\017\n\007emailId\030\002 \001(\t\022" +
      "\020\n\010password\030\003 \001(\t\"K\n\016changePassword\022\017\n\007e" +
      "mailId\030\001 \001(\t\022\023\n\013oldPassword\030\002 \001(\t\022\023\n\013new" +
      "Password\030\003 \001(\t\"\031\n\010response\022\r\n\005reply\030\001 \001(" +
      "\t\"*\n\005login\022\017\n\007emailId\030\001 \001(\t\022\020\n\010password\030" +
      "\002 \001(\t2\362\001\n\024loginAndRegistration\022H\n\010Regist" +
      "er\022\037.loginRegistration.registration\032\033.lo" +
      "ginRegistration.response\022>\n\005Login\022\030.logi" +
      "nRegistration.login\032\033.loginRegistration." +
      "response\022P\n\016ChangePassword\022!.loginRegist" +
      "ration.changePassword\032\033.loginRegistratio" +
      "n.responseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_loginRegistration_registration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loginRegistration_registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRegistration_registration_descriptor,
        new java.lang.String[] { "Name", "EmailId", "Password", });
    internal_static_loginRegistration_changePassword_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loginRegistration_changePassword_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRegistration_changePassword_descriptor,
        new java.lang.String[] { "EmailId", "OldPassword", "NewPassword", });
    internal_static_loginRegistration_response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_loginRegistration_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRegistration_response_descriptor,
        new java.lang.String[] { "Reply", });
    internal_static_loginRegistration_login_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_loginRegistration_login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loginRegistration_login_descriptor,
        new java.lang.String[] { "EmailId", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
