// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package loginRegistration;

public interface loginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginRegistration.login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emailId = 1;</code>
   * @return The emailId.
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 1;</code>
   * @return The bytes for emailId.
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
