// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package loginRegistration;

public interface registrationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loginRegistration.registration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string emailId = 2;</code>
   * @return The emailId.
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 2;</code>
   * @return The bytes for emailId.
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
