// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package TCD.helloGRPC;

public interface responseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TCD.helloGRPC.response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
